dotnet nuget push FunctionMonkey.4.*.nupkg --api-key $NUGETKEY --source https://api.nuget.org/v3/index.json
dotnet nuget push FunctionMonkey.Abstractions.*.nupkg --api-key $NUGETKEY --source https://api.nuget.org/v3/index.json
dotnet nuget push FunctionMonkey.AspNetCore.*.nupkg --api-key $NUGETKEY --source https://api.nuget.org/v3/index.json
dotnet nuget push FunctionMonkey.Commanding.Abstractions.*.nupkg --api-key $NUGETKEY --source https://api.nuget.org/v3/index.json
dotnet nuget push FunctionMonkey.Commanding.Cosmos.Abstractions.*.nupkg --api-key $NUGETKEY --source https://api.nuget.org/v3/index.json
dotnet nuget push FunctionMonkey.Compiler.*.nupkg --api-key $NUGETKEY --source https://api.nuget.org/v3/index.json
dotnet nuget push FunctionMonkey.FSharp.*.nupkg --api-key $NUGETKEY --source https://api.nuget.org/v3/index.json
dotnet nuget push FunctionMonkey.FluentValidation.*.nupkg --api-key $NUGETKEY --source https://api.nuget.org/v3/index.json
dotnet nuget push FunctionMonkey.MediatR.*.nupkg --api-key $NUGETKEY --source https://api.nuget.org/v3/index.json
dotnet nuget push FunctionMonkey.SignalR.*.nupkg --api-key $NUGETKEY --source https://api.nuget.org/v3/index.json
dotnet nuget push FunctionMonkey.Testing.*.nupkg --api-key $NUGETKEY --source https://api.nuget.org/v3/index.json
dotnet nuget push FunctionMonkey.TokenValidator.*.nupkg --api-key $NUGETKEY --source https://api.nuget.org/v3/index.json
